import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, DM_Serif_Text, Hanken_Grotesk} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UserContextProvider } from "@/context/UserContext";
import { getSession } from "@/lib/actions/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const dmSerif = DM_Serif_Text({
  variable: "--font-dm-serif",
  subsets: ["latin"],
  weight: "400",
  style: "italic"
});

const hankenGrotesk = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session = await getSession()

  return (
    <html lang="en">
      <UserContextProvider initialUser={session?.user || null}>

      <body
        className={`${geistSans.variable} ${poppins.variable} ${dmSerif.variable} ${hankenGrotesk.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        <Toaster />
      </body>
        </UserContextProvider>
    </html>
  );
}
